model: spanbert-large-cased
data_dir: /home/ec2-user/data/json/relabeled2_0
#data_dir: /home/ec2-user/data/json
#eval_path: /home/ec2-user/data/json/relabeled2_0/patched/test_clean.json
eval_path: /home/ec2-user/data/json/test.json
output_dir:
indices_load_path: #/home/ec2-user/apex/SpanBERT/indices_dir/baseline/wrong_ids.txt
eval_per_epoch: 10
max_seq_length: 128
negative_label: "no_relation"
# What to run
do_train: False
train_mode: random_sorted # choices: ['random', 'sorted', 'random_sorted']
do_eval: True
eval_test: True

do_lower_case: False
feature_mode: ner
train_batch_size: 16
eval_batch_size: 32
eval_metric: f1
learning_rate: 0.00002 # Play with the LR. Reduce the LR
num_train_epochs: 10
warmup_proportion: .1
no_cuda: False
seed: 0
gradient_accumulation_steps: 2
fp16: True
loss_scale: 2
data_type: patched
version: clean
with_jrrelp: False
#jrrelp_lambda: .1
#without_observed: False
#without_verification: False
#exclude_no_relation: False
